### PR TITLE
RNMT-5730 Add required customisations to Cordova-android 11.0.0

### PR DESCRIPTION
**Pull request by usernuno**
## Description

The following customisations from our 10.1.1 version were handled:
- **Escape strings.xml app name:** this was already merged in 11, but we have extra test coverage on our side, so this coverage was kept
- **Enable filter touches:** not merged, so it was kept on our side

New customisations were added:
- **Error on Cordova loading error.html:** this has been in the template forever as a patch, now it was moved to the engine (there are no more patches in the template)
- **Re-introduce legacy Cordova splash screen logic:** this a bit complex, let's dive into details below

### Splash screen changes
Cordova-android 11 updated the Splash Screen UX to conform to Google's guidelines. It now no longer uses the `cordova-plugin-splashscreen`. This plugin was now moved to the engine as a core plugin, and its logic was very simplified:
- Use the Android Splash Screen API, controlled by a theme (this allows the customisation of a background color, a central icon + icon background, and a branding image)
- No longer uses an ImageView for the full image splashes and the spinner (support for this was dropped)
- Use the AndroidX compat library for the SplashScreen API so the experience is the same on all Android versions (and not differ between Android 11/12 devices)
- Add preferences to customise the elements described in the first point
- `show()` is unavailable because this native splash screen cannot be shown again

This is a good change but it's problematic for OutSystems, as we support the full image splashes and presenting a spinner. Both of these options are still available for iOS.

So what can we do to take advantage of all these wins but still have access to the older features?
- Modify the engine to reintroduce the old code, next to the new one
- If no custom splash screens or spinner are used, don't use the old code (gives the new Google intended UX)
- If either is used, use both experiences (like in MABS 8), presenting the Android splash as little as possible and using the values in the preferences for the Cordova legacy splash
- In case of the latter, reinstate the behaviour of the `show()` method, while keeping it as no-op for the new UX

With this we can embrace modernity while still supporting all the use cases.

Caveats:
- Using a branding image seems to make the app crash, because it's not supported by the compat library. There is an [unreleased fix](https://github.com/apache/cordova-android/commit/954d3e0e7542356e6ea995ddc75dcb1db8bb36cc) for this, but fixing it would still give a different UX between Android 11/12 devices. Might as well not document the preference and letting it crash if used.
- Since detecting that custom splash screens are used must be done in the Worker, a preference was created for this. The preference is `HasCustomSplashscreens`, but `HasCustomIcons` was also created for "parity". The customer can take advantage of changing the value of this preference to `true` to use the old UX, even without custom splash screens or the spinner (remember that images are always generated by the Worker, even if just full color ones).

## Context

Closes https://outsystemsrd.atlassian.net/browse/RNMT-5730

- Commit by commit review is recommended
- Disabling whitespace diff can help understand what was done regarding the SplashScreen merge

## Type of changes

- [x] Feature (change which adds functionality)
    - [ ] BREAKING CHANGE (existing functionality will not work as expected due to new feature)
- [x] Fix (change which fixes an issue)
    - [ ] BREAKING CHANGE (existing functionality will not work as expected due to fix)
- [ ] Performance (change which improves performance)
    - [ ] BREAKING CHANGE (existing functionality will not work as expected due to performance improvement)
- [ ] Refactor (non-breaking change that is neither feature, fix nor performance)
- [ ] Style (non-breaking change that only affects formatting and/or white-space)

## Tests

Manual tests were performed with builds generated by the local Worker. All preferences, along with the `show()` / `hide()` were exercised.

## Checklist

- [x] Pull request title follows the format `RNMT-XXXX <title>`
- [ ] Tests have been created
- [x] Code follows code style of this project
- [ ] CHANGELOG.md file is correctly updated
- [x] Changes require an update to the documentation
    - [ ] Documentation has been updated accordingly

### CODE REVIEW

**Review by cmfsotelo — APPROVED** [review]
Nice,

I have one question though, for clarification.

When we c onfigure the "legacy" splashscreen, all the common settings are being fed only into the legacy version right? 

for instance, If I configure delay time and configure legacy splashscreens, it will only delay on the legacy.

https://github.com/OutSystems/cordova-android/pull/12/files#diff-1027219773ff9d586901f05c44d1df57ac92953206cca9dcfa2a0546c35c3512R110

**Comment by usernuno** [comment]
> Nice,
> 
> I have one question though, for clarification.
> 
> When we c onfigure the "legacy" splashscreen, all the common settings are being fed only into the legacy version right?
> 
> for instance, If I configure delay time and configure legacy splashscreens, it will only delay on the legacy.
> 
> https://github.com/OutSystems/cordova-android/pull/12/files#diff-1027219773ff9d586901f05c44d1df57ac92953206cca9dcfa2a0546c35c3512R110

Yes, the values are hammered here: https://github.com/OutSystems/cordova-android/blob/753ff8d4f13b2c713bce3632d8ed1c9322810461/framework/src/org/apache/cordova/SplashScreenPlugin.java#L110

Simplifying the management of this interaction is the main reason for the usage of the separated behaviours.

**Comment by cmfsotelo** [comment]
> 

I thought the link I posted was precisely for those lines 😓

**Comment by cmfsotelo** [comment]
> > Nice,
> > I have one question though, for clarification.
> > When we c onfigure the "legacy" splashscreen, all the common settings are being fed only into the legacy version right?
> > for instance, If I configure delay time and configure legacy splashscreens, it will only delay on the legacy.
> > https://github.com/OutSystems/cordova-android/pull/12/files#diff-1027219773ff9d586901f05c44d1df57ac92953206cca9dcfa2a0546c35c3512R110
> 
> Yes, the values are hammered here:
> 
> https://github.com/OutSystems/cordova-android/blob/753ff8d4f13b2c713bce3632d8ed1c9322810461/framework/src/org/apache/cordova/SplashScreenPlugin.java#L110
> 
> Simplifying the management of this interaction is the main reason for the usage of the separated behaviours.


I thought the link I posted was precisely for those lines 😓

**Review by EiyuuZack — APPROVED** [review]
🍻 to embracing modernity

**Pull request merged**
